### ISSUE TITLE
Suggest ignoring pycache and jupyter notebook checkpoints directories

### ISSUE THREAD

**Issue by tomalrussell** [njleach/GIR#1]
Hi @njleach , @stujen - I was pointed to this project by a student (Robyn), who's looking at using the simple GIR model. It looks really neat, particularly how it's starting to shape up with the core model code separate from example analysis notebooks.

This is a minor housekeeping suggestion. It's generally good practice to ignore temporary or cache files in git repositories, like the `.pyc` files stored in `__pycache__` or the intermediate versions of notebooks held in `.ipynb_checkpoints`. All the important information is held in the main source code, there's no need to keep the cached or intermediate files too.

I'll open a quick pull request, hope it's useful.

**Comment by njleach** [comment]
Hi @tomalrussell. Thanks very much for the interest and suggestion! At some point I will likely have a proper clear and organise of this repo as it's pretty messy, but this probably won't happen for a little while as I'm still working on some development stuff.
Cheers, Nick

**Comment by tomalrussell** [comment]
Hi Nick, sure thing - I'm glad the uninvited PR landed okay with you!

For info, if you want another pair of eyes on this code (or other projects) at some point, I can recommend things like the [Oxford Code Review Network](https://github.com/OxfordCodeReviewNet/forum/) or the review process attached to a [JOSS](https://joss.theoj.org/) submission.
